package com.robin.tools.ui.theme

import androidx.compose.ui.graphics.Color

// Blueprint workbench — dark theme
val DarkBackground = Color(0xFF0B1523)
val DarkSurface = Color(0xFF102238)
val DarkSurfaceVariant = Color(0xFF172B3D)
val DarkSurfaceContainerHigh = Color(0xFF20384D)
val DarkOnSurface = Color(0xFFDDEBFA)
val DarkOnSurfaceVariant = Color(0xFFAFC1D2)
val DarkPrimary = Color(0xFF48D8EE)
val DarkSecondary = Color(0xFFD7ED78)
val DarkTertiary = Color(0xFFFF9C80)
val DarkError = Color(0xFFFFB4AB)
val DarkOnPrimary = Color(0xFF00363E)
val DarkOnSecondary = Color(0xFF2A3400)
val DarkOnTertiary = Color(0xFF5C1A09)
val DarkOnError = Color(0xFF690005)
val DarkPrimaryContainer = Color(0xFF005F6D)
val DarkOnPrimaryContainer = Color(0xFF9CF0FF)
val DarkSecondaryContainer = Color(0xFF4B5A00)
val DarkOnSecondaryContainer = Color(0xFFECFF9E)
val DarkTertiaryContainer = Color(0xFF81250F)
val DarkOnTertiaryContainer = Color(0xFFFFDBD0)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)

// Blueprint workbench — light theme
val LightBackground = Color(0xFFF3F7FA)
val LightSurface = Color(0xFFFBFCFE)
val LightSurfaceVariant = Color(0xFFE4EDF4)
val LightSurfaceContainerHigh = Color(0xFFD8E4EC)
val LightOnSurface = Color(0xFF102238)
val LightOnSurfaceVariant = Color(0xFF4D6173)
val LightPrimary = Color(0xFF007F94)
val LightSecondary = Color(0xFF657A1B)
val LightTertiary = Color(0xFFD75A3A)
val LightError = Color(0xFFBA1A1A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightOnError = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB2EBF5)
val LightOnPrimaryContainer = Color(0xFF001F25)
val LightSecondaryContainer = Color(0xFFD9F0A4)
val LightOnSecondaryContainer = Color(0xFF182000)
val LightTertiaryContainer = Color(0xFFFFDBD0)
val LightOnTertiaryContainer = Color(0xFF3D0800)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
